import { NextResponse } from 'next/server';
import connectDB from '@/lib/mongodb';
import KeywordCache from '@/models/KeywordCache';
import Post from '@/models/Post';
import OpenAI from 'openai';
import { createApi } from 'unsplash-js';

const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY!,
});

const unsplash = createApi({
  accessKey: process.env.UNSPLASH_ACCESS_KEY!,
});

export const dynamic = 'force-dynamic';
export const revalidate = 0;
export const maxDuration = 60;

function generateSlug(title: string): string {
  return title
    .toLowerCase()
    .replace(/[^ㄱ-힝a-z0-9\s-]/g, '')
    .replace(/\s+/g, '-')
    .replace(/--+/g, '-')
    .replace(/^-+|-+$/g, '');
}

export async function POST(request: Request) {
  try {
    await connectDB();

    const { keywordCount } = await request.json();
    if (!keywordCount || keywordCount < 1 || keywordCount > 5) {
      return NextResponse.json(
        { error: '키워드 개수는 1~5개 사이여야 합니다.' },
        { status: 400 }
      );
    }

    const unusedKeywords = await KeywordCache.find({ used: false });
    if (unusedKeywords.length < keywordCount) {
      return NextResponse.json(
        { error: '사용 가능한 키워드가 부족합니다.' },
        { status: 400 }
      );
    }

    const selectedKeywords = unusedKeywords.sort(() => 0.5 - Math.random()).slice(0, keywordCount);
    const createdPosts = [];

    for (const { keyword, _id } of selectedKeywords) {
      try {
        const prompt = `
          당신은 트렌드 분석 블로그 작가입니다. 아래 키워드를 바탕으로 블로그 글을 작성해 주세요.

          작성 규칙:
          - 전체 글자 수는 **1000자 이상**이어야 합니다. 부족할 경우 실패 처리됩니다.
          - 마크다운 형식으로 문단을 구성해 주세요 (## 소제목 포함)
          - 소제목은 현실적인 제목으로 3개 이상 사용해 주세요.
          - 소제목은 자연스럽고 현실적인 제목으로 작성해주세요 (예: '왜 사람들이 이 경기에 열광할까?').
          - 블로그 스타일로 문장마다 독자 친화적이고 자연스럽게 작성해 주세요.

          결과는 아래 JSON 형식으로만 응답하세요. JSON 외 텍스트는 절대 포함하지 마세요.

          {
            "title": "자연스러운 블로그 제목 (한국어)",
            "content": "# 서론\\n\\n(도입부 300자 이상)\\n\\n## 트렌드 분석\\n\\n(500자 이상 설명)\\n\\n## 최근 반응\\n\\n(500자 이상 사례 및 반응)\\n\\n## 결론\\n\\n(200자 이상 요약)",
            "hashtags": ["태그1", "태그2", "태그3", "태그4", "태그5"],
            "imageQuery": "이미지 검색용 영어 키워드"
          }

          키워드: ${keyword}
          `;

        const gptResponse = await openai.chat.completions.create({
          model: 'gpt-3.5-turbo',
          messages: [{ role: 'user', content: prompt }],
          temperature: 0.7,
          max_tokens: 3000,
        });

        if (!gptResponse?.choices?.[0]?.message?.content) {
          throw new Error('GPT 응답이 유효하지 않습니다.');
        }

        let parsedResponse;
        try {
          const raw = gptResponse.choices[0].message.content;
          const jsonMatch = raw.match(/\{[\s\S]*\}/);
          if (!jsonMatch) {
            throw new Error("GPT 응답이 유효한 JSON 형식이 아닙니다.");
          }

          parsedResponse = JSON.parse(jsonMatch[0]);

          if (!parsedResponse.title || !parsedResponse.content) {
            throw new Error('필수 필드가 누락되었습니다.');
          }

          parsedResponse.content = parsedResponse.content
            .replace(/!\[.*?\]\(.*?\)/g, '')
            .replace(/https?:\/\/[\S]+\.(jpg|jpeg|png|gif|webp)/gi, '')
            .trim();

          if (!Array.isArray(parsedResponse.hashtags) || parsedResponse.hashtags.length === 0) {
            parsedResponse.hashtags = [keyword];
          }

        } catch (error) {
          throw new Error(`GPT 응답 처리 실패: ${error instanceof Error ? error.message : '알 수 없는 오류'}`);
        }

        let imageUrl = '';
        try {
          const query = parsedResponse.imageQuery || parsedResponse.title || keyword;
          const imageResponse = await unsplash.photos.getRandom({ query, count: 1 });

          if (Array.isArray(imageResponse.response)) {
            imageUrl = imageResponse.response[0]?.urls?.regular || '';
          } else if (imageResponse.response?.urls?.regular) {
            imageUrl = imageResponse.response.urls.regular;
          }
        } catch (_) {
          // 이미지 가져오기 실패 시 무시
        }

        const post = await Post.create({
          title: parsedResponse.title || keyword,
          slug: generateSlug(parsedResponse.title || keyword),
          content: parsedResponse.content,
          imageUrl,
          tags: parsedResponse.hashtags || [keyword],
          metadata: {
            autoGenerated: true,
            keywords: [keyword],
          },
        });

        await KeywordCache.findByIdAndUpdate(_id, { used: true });

        createdPosts.push({
          _id: post._id,
          title: post.title,
          content: post.content,
          imageUrl: post.imageUrl,
          tags: post.tags,
          createdAt: post.createdAt,
        });
      } catch (_) {
        continue;
      }
    }

    if (createdPosts.length === 0) {
      return NextResponse.json(
        { error: '포스트 생성에 실패했습니다.' },
        { status: 500 }
      );
    }

    return NextResponse.json({
      message: '포스트가 성공적으로 생성되었습니다.',
      count: createdPosts.length,
      posts: createdPosts,
    });
  } catch (error) {
    return NextResponse.json(
      { error: error instanceof Error ? error.message : '포스트 생성 중 오류가 발생했습니다.' },
      { status: 500 }
    );
  }
}
