import { NextResponse } from 'next/server';
import connectDB from '@/lib/mongodb';
import Post from '@/models/Post';

export const dynamic = 'force-dynamic';
export const revalidate = 0;

export async function GET() {
  try {
    await connectDB();

    const posts = await Post.find({
      'metadata.autoGenerated': true
    }).sort({ createdAt: -1 });

    return NextResponse.json({
      posts: posts.map(post => ({
        _id: post._id,
        title: post.title,
        content: post.content,
        imageUrl: post.imageUrl,
        tags: post.tags,
        createdAt: post.createdAt,
        metadata: post.metadata
      }))
    });
  } catch (error) {
    console.error('자동 생성 포스트 조회 에러:', error);
    return NextResponse.json(
      { error: '자동 생성 포스트 조회 중 오류가 발생했습니다.' },
      { status: 500 }
    );
  }
} 