const post = await Post.create({
  title: generatedTitle,
  content: generatedContent,
  category: 'trend',
  keywords: keywords,
  metadata: {
    autoGenerated: true,
    generationSource: 'gpt',
    originalTopic: topic,
    searchKeywords: keywords,
    imageKeywords: imageKeywords
  }
}); 