import mongoose from 'mongoose';

const postSchema = new mongoose.Schema({
  title: {
    type: String,
    required: true,
    trim: true
  },
  content: {
    type: String,
    required: true
  },
  createdAt: {
    type: Date,
    default: Date.now
  },
  keywords: [{
    type: String,
    trim: true
  }],
  views: {
    type: Number,
    default: 0
  },
  likes: {
    type: Number,
    default: 0
  },
  imageUrl: {
    type: String,
    trim: true
  },
  slug: {
    type: String,
    trim: true,
    unique: true,
    sparse: true
  },
  description: String,
  featuredImage: {
    url: String,
    alt: String,
    credit: {
      name: String,
      url: String
    }
  },
  viewCount: { type: Number, default: 0 },
  likeCount: { type: Number, default: 0 },
  metadata: {
    autoGenerated: {
      type: Boolean,
      default: false,
    },
    generationSource: String,
    originalTopic: String,
    searchKeywords: [String],
    imageKeywords: [String]
  },
  views: {
    type: Number,
    default: 0,
  },
  likes: {
    type: Number,
    default: 0,
  },
}, {
  timestamps: true,
});

export default mongoose.models.Post || mongoose.model('Post', postSchema); 